### ISSUE TITLE
Errors on swap

### ISSUE THREAD

**Issue by elliotwesoff** [riddlew/swap-split.nvim#1]
This plugin has actually never successfully swapped a window for me. When I run :SwapSplit, it prompts me for the destination buffer, I press the letter and I get this error message:

```
   Error  E5108: Error executing lua ...ite/pack/packer/start/swap-split.nvim/lua/swap-split.lua:89: Invalid window id: 1053
stack traceback:
	[C]: in function 'nvim_win_set_option'
	...ite/pack/packer/start/swap-split.nvim/lua/swap-split.lua:89: in function 'select_win'
	...ite/pack/packer/start/swap-split.nvim/lua/swap-split.lua:114: in function 'swap'
	[string ":lua"]:1: in main chunk
```

**Comment by riddlew** [comment]
I pushed a small fix. Please update the plugin and let me know if that fixes your issue.

**Comment by elliotwesoff** [comment]
@cloudysake it works now, thank you so much!
